INSERT INTO levels (level_number, title, cefr_band, description, required_vocab_count, unlock_score_threshold) VALUES
(1, 'Daily Conversational Basics', 'A1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A1 level proficiency.', 17, 80.0),
(2, 'Expressing Preferences', 'A1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A1 level proficiency.', 19, 80.0),
(3, 'Ordering & Dining Out', 'A1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A1 level proficiency.', 21, 80.0),
(4, 'Travel & Directions', 'A1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A1 level proficiency.', 23, 80.0),
(5, 'Hobbies & Leisure', 'A1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A1 level proficiency.', 25, 80.0),
(6, 'Describing People & Places', 'A1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A1 level proficiency.', 27, 80.0),
(7, 'Workplace Essentials', 'A1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A1 level proficiency.', 29, 80.0),
(8, 'Making Plans & Invites', 'A1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A1 level proficiency.', 31, 80.0),
(9, 'Past Experiences', 'A1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A1 level proficiency.', 33, 80.0),
(10, 'Future Intentions', 'A1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A1 level proficiency.', 15, 80.0),
(11, 'Opinion & Arguments', 'A1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A1 level proficiency.', 17, 80.0),
(12, 'Shopping & Bargaining', 'A1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A1 level proficiency.', 19, 80.0),
(13, 'Nuanced Emotions', 'A1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A1 level proficiency.', 21, 80.0),
(14, 'Business Email Etiquette', 'A1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A1 level proficiency.', 23, 80.0),
(15, 'Problem Solving & Advice', 'A1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A1 level proficiency.', 25, 80.0),
(16, 'Cultural Etiquette', 'A2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A2 level proficiency.', 27, 80.0),
(17, 'Telephone & Video Calls', 'A2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A2 level proficiency.', 29, 80.0),
(18, 'Health & Wellness', 'A2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A2 level proficiency.', 31, 80.0),
(19, 'Technology & Innovation', 'A2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A2 level proficiency.', 33, 80.0),
(20, 'Media & Entertainment', 'A2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A2 level proficiency.', 15, 80.0),
(21, 'Professional Networking', 'A2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A2 level proficiency.', 17, 80.0),
(22, 'Expressing Agreement & Doubt', 'A2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A2 level proficiency.', 19, 80.0),
(23, 'Job Interviews', 'A2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A2 level proficiency.', 21, 80.0),
(24, 'Financial Terminology', 'A2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A2 level proficiency.', 23, 80.0),
(25, 'Environmental Discussions', 'A2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A2 level proficiency.', 25, 80.0),
(26, 'Storytelling & Narratives', 'A2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A2 level proficiency.', 27, 80.0),
(27, 'Hypothetical Scenarios', 'A2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A2 level proficiency.', 29, 80.0),
(28, 'Idioms & Phrasal Verbs', 'A2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A2 level proficiency.', 31, 80.0),
(29, 'Debating Complex Topics', 'A2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A2 level proficiency.', 33, 80.0),
(30, 'Project Management', 'A2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for A2 level proficiency.', 15, 80.0),
(31, 'Negotiations & Persuasion', 'B1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B1 level proficiency.', 17, 80.0),
(32, 'Art & Literature Analysis', 'B1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B1 level proficiency.', 19, 80.0),
(33, 'Scientific Concepts', 'B1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B1 level proficiency.', 21, 80.0),
(34, 'Abstract Thought', 'B1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B1 level proficiency.', 23, 80.0),
(35, 'Formal Presentation Skills', 'B1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B1 level proficiency.', 25, 80.0),
(36, 'Cross-Cultural Communication', 'B1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B1 level proficiency.', 27, 80.0),
(37, 'Conflict Resolution', 'B1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B1 level proficiency.', 29, 80.0),
(38, 'Subtle Humor & Irony', 'B1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B1 level proficiency.', 31, 80.0),
(39, 'Diplomatic Language', 'B1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B1 level proficiency.', 33, 80.0),
(40, 'Academic Writing', 'B1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B1 level proficiency.', 15, 80.0),
(41, 'Current Affairs & Politics', 'B1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B1 level proficiency.', 17, 80.0),
(42, 'Legal & Ethical Issues', 'B1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B1 level proficiency.', 19, 80.0),
(43, 'Philosophical Inquiry', 'B1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B1 level proficiency.', 21, 80.0),
(44, 'Leadership & Vision', 'B1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B1 level proficiency.', 23, 80.0),
(45, 'Mastering Metaphors', 'B1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B1 level proficiency.', 25, 80.0),
(46, 'Advanced Rhetoric', 'B2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B2 level proficiency.', 27, 80.0),
(47, 'Crisis Management', 'B2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B2 level proficiency.', 29, 80.0),
(48, 'Public Speaking Mastery', 'B2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B2 level proficiency.', 31, 80.0),
(49, 'Advanced Argumentation', 'B2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B2 level proficiency.', 33, 80.0),
(50, 'Native Conversational Nuance', 'B2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B2 level proficiency.', 15, 80.0),
(51, 'Sophisticated Vocabulary', 'B2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B2 level proficiency.', 17, 80.0),
(52, 'Colloquial Expressions', 'B2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B2 level proficiency.', 19, 80.0),
(53, 'Advanced Business Strategy', 'B2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B2 level proficiency.', 21, 80.0),
(54, 'Diplomatic Protocol', 'B2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B2 level proficiency.', 23, 80.0),
(55, 'Literary Analysis', 'B2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B2 level proficiency.', 25, 80.0),
(56, 'Scientific Discourse', 'B2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B2 level proficiency.', 27, 80.0),
(57, 'Complex Problem Solving', 'B2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B2 level proficiency.', 29, 80.0),
(58, 'Advanced Negotiation Skills', 'B2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B2 level proficiency.', 31, 80.0),
(59, 'Cross-Cultural Mastery', 'B2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B2 level proficiency.', 33, 80.0),
(60, 'Public Relations & Media', 'B2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for B2 level proficiency.', 15, 80.0),
(61, 'Executive Communication', 'C1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C1 level proficiency.', 17, 80.0),
(62, 'Philosophical Debate', 'C1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C1 level proficiency.', 19, 80.0),
(63, 'Legal Advocacy', 'C1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C1 level proficiency.', 21, 80.0),
(64, 'Strategic Vision', 'C1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C1 level proficiency.', 23, 80.0),
(65, 'Rhetorical Mastery', 'C1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C1 level proficiency.', 25, 80.0),
(66, 'Creative Storytelling', 'C1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C1 level proficiency.', 27, 80.0),
(67, 'Global Affairs Analysis', 'C1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C1 level proficiency.', 29, 80.0),
(68, 'Ethical Leadership', 'C1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C1 level proficiency.', 31, 80.0),
(69, 'Advanced Metaphorical Use', 'C1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C1 level proficiency.', 33, 80.0),
(70, 'Crisis Communication', 'C1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C1 level proficiency.', 15, 80.0),
(71, 'High-Stakes Presentation', 'C1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C1 level proficiency.', 17, 80.0),
(72, 'Advanced Conflict Resolution', 'C1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C1 level proficiency.', 19, 80.0),
(73, 'Sophisticated Humor & Satire', 'C1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C1 level proficiency.', 21, 80.0),
(74, 'Academic Research Presentation', 'C1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C1 level proficiency.', 23, 80.0),
(75, 'Diplomatic Negotiations', 'C1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C1 level proficiency.', 25, 80.0),
(76, 'Executive Leadership', 'C1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C1 level proficiency.', 27, 80.0),
(77, 'Mastering Vernacular', 'C1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C1 level proficiency.', 29, 80.0),
(78, 'Advanced Academic Writing', 'C1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C1 level proficiency.', 31, 80.0),
(79, 'Global Economics', 'C1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C1 level proficiency.', 33, 80.0),
(80, 'Philosophical Discourse', 'C1', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C1 level proficiency.', 15, 80.0),
(81, 'Native-Level Precision', 'C2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C2 level proficiency.', 17, 80.0),
(82, 'Mastering Nuance & Subtlety', 'C2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C2 level proficiency.', 19, 80.0),
(83, 'High-Level Rhetorical Devices', 'C2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C2 level proficiency.', 21, 80.0),
(84, 'Advanced Persuasive Speaking', 'C2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C2 level proficiency.', 23, 80.0),
(85, 'Executive Diplomacy', 'C2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C2 level proficiency.', 25, 80.0),
(86, 'Mastering Idiomatic Expressions', 'C2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C2 level proficiency.', 27, 80.0),
(87, 'Literary & Cultural Criticism', 'C2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C2 level proficiency.', 29, 80.0),
(88, 'Strategic Negotiation', 'C2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C2 level proficiency.', 31, 80.0),
(89, 'Advanced Public Advocacy', 'C2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C2 level proficiency.', 33, 80.0),
(90, 'Complex Ethical Debates', 'C2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C2 level proficiency.', 15, 80.0),
(91, 'Executive Public Speaking', 'C2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C2 level proficiency.', 17, 80.0),
(92, 'Global Diplomacy', 'C2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C2 level proficiency.', 19, 80.0),
(93, 'Native-Level Fluency & Elegance', 'C2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C2 level proficiency.', 21, 80.0),
(94, 'Mastery of Abstract Concepts', 'C2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C2 level proficiency.', 23, 80.0),
(95, 'Sophisticated Rhetorical Analysis', 'C2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C2 level proficiency.', 25, 80.0),
(96, 'Executive Communication Excellence', 'C2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C2 level proficiency.', 27, 80.0),
(97, 'Mastery of Subtle Irony & Wit', 'C2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C2 level proficiency.', 29, 80.0),
(98, 'Native-Level Spontaneous Discourse', 'C2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C2 level proficiency.', 31, 80.0),
(99, 'Ultimate Linguistic Mastery', 'C2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C2 level proficiency.', 33, 80.0),
(100, 'LingoLive Grandmaster', 'C2', 'Master key sentence structures, idioms, and fluent vocabulary tailored for C2 level proficiency.', 15, 80.0)
ON CONFLICT (level_number) DO NOTHING;
