const fs = require('fs');
const path = require('path');

const dataPath = path.join(__dirname, 'frontend', 'src', 'data', 'malayalamWordsData.json');
const currentData = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

const newPayload = {
  "language": "Malayalam",
  "code": "ml",
  "total_words": 100,
  "words": [
    { "malayalam": "നഗരം", "english_transliteration": "Nagaram", "tamil_transliteration": "நகரம்", "english_meaning": "City", "tamil_meaning": "நகரம்" },
    { "malayalam": "ഗ്രാമം", "english_transliteration": "Gramam", "tamil_transliteration": "கிராமம்", "english_meaning": "Village", "tamil_meaning": "கிராமம்" },
    { "malayalam": "തെരുവ്", "english_transliteration": "Theruvu", "tamil_transliteration": "தெருவு", "english_meaning": "Street", "tamil_meaning": "தெரு" },
    { "malayalam": "വീഥി", "english_transliteration": "Veethi", "tamil_transliteration": "வீதி", "english_meaning": "Lane / Pathway", "tamil_meaning": "வீதி" },
    { "malayalam": "പാലം", "english_transliteration": "Paalam", "tamil_transliteration": "பாலம்", "english_meaning": "Bridge", "tamil_meaning": "பாலம்" },
    { "malayalam": "കെട്ടിടം", "english_transliteration": "Kettidam", "tamil_transliteration": "கெட்டிடம்", "english_meaning": "Building", "tamil_meaning": "கட்டிடம்" },
    { "malayalam": "ഗോപുരം", "english_transliteration": "Gopuram", "tamil_transliteration": "கோபுரம்", "english_meaning": "Tower", "tamil_meaning": "கோபுரம்" },
    { "malayalam": "അമ്പലം", "english_transliteration": "Ambalam", "tamil_transliteration": "அம்பலம்", "english_meaning": "Temple", "tamil_meaning": "கோவில்" },
    { "malayalam": "പള്ളി", "english_transliteration": "Palli", "tamil_transliteration": "பள்ளி", "english_meaning": "Mosque / Church", "tamil_meaning": "பள்ளிவாசல் / தேவாலயம்" },
    { "malayalam": "മ്യൂസിയം", "english_transliteration": "Museum", "tamil_transliteration": "மியூசியம்", "english_meaning": "Museum", "tamil_meaning": "அருங்காட்சியகம்" },
    { "malayalam": "ഗ്രന്ഥശാല", "english_transliteration": "Granthashala", "tamil_transliteration": "கிரந்தசாலா", "english_meaning": "Library", "tamil_meaning": "நூலகம்" },
    { "malayalam": "പാർക്ക്", "english_transliteration": "Park", "tamil_transliteration": "பார்க்", "english_meaning": "Park", "tamil_meaning": "பூங்கா" },
    { "malayalam": "മൃഗശാല", "english_transliteration": "Mrigashala", "tamil_transliteration": "ம்ருகசாலா", "english_meaning": "Zoo", "tamil_meaning": "விலங்குக்காட்சிச்சாலை" },
    { "malayalam": "വിമാനത്താവളം", "english_transliteration": "Vimanathavalam", "tamil_transliteration": "விமானத்தாவளம்", "english_meaning": "Airport", "tamil_meaning": "விமான நிலையம்" },
    { "malayalam": "റെയിൽവേ സ്റ്റേഷൻ", "english_transliteration": "Railway Station", "tamil_transliteration": "ரயில்வே ஸ்டேஷன்", "english_meaning": "Railway Station", "tamil_meaning": "ரெயில் நிலையம்" },
    { "malayalam": "ബസ് സ്റ്റാൻഡ്", "english_transliteration": "Bus Stand", "tamil_transliteration": "பஸ் ஸ்டாண்ட்", "english_meaning": "Bus Stand", "tamil_meaning": "பேருந்து நிலையம்" },
    { "malayalam": "തുറമുഖം", "english_transliteration": "Thuramukham", "tamil_transliteration": "துறமுகம்", "english_meaning": "Harbor / Port", "tamil_meaning": "துறைமுகம்" },
    { "malayalam": "തീരപ്രദേശം", "english_transliteration": "Theerapradesham", "tamil_transliteration": "தீிரப்பிரதேசம்", "english_meaning": "Coastal Area", "tamil_meaning": "கடற்கரை பகுதி" },
    { "malayalam": "ദ്വീപ്", "english_transliteration": "Dweepu", "tamil_transliteration": "த்வீபு", "english_meaning": "Island", "tamil_meaning": "தீவு" },
    { "malayalam": "പെനിൻസുല", "english_transliteration": "Peninsula", "tamil_transliteration": "பெனின்சுலா", "english_meaning": "Peninsula", "tamil_meaning": "தீபகற்பம்" },
    { "malayalam": "ഉപദ്വീപ്", "english_transliteration": "Upadweepu", "tamil_transliteration": "உபத்வீபு", "english_meaning": "Sub-island", "tamil_meaning": "சிறிய தீவு" },
    { "malayalam": "വനം", "english_transliteration": "Vanam", "tamil_transliteration": "வனம்", "english_meaning": "Forest", "tamil_meaning": "காடு" },
    { "malayalam": "ചതുപ്പ്", "english_transliteration": "Chathuppu", "tamil_transliteration": "சதுப்பு", "english_meaning": "Swamp", "tamil_meaning": "சதுப்பு நிலம்" },
    { "malayalam": "മരുഭൂമി", "english_transliteration": "Marubhoomi", "tamil_transliteration": "மருபூமி", "english_meaning": "Desert", "tamil_meaning": "பாலைவனம்" },
    { "malayalam": "പർവ്വതം", "english_transliteration": "Parvatham", "tamil_transliteration": "பர்வத்", "english_meaning": "Mountain", "tamil_meaning": "மலை" },
    { "malayalam": "കുന്നിൻപുറം", "english_transliteration": "Kunninpuram", "tamil_transliteration": "குன்றின்புறம்", "english_meaning": "Hilltop", "tamil_meaning": "குன்றின் மீது" },
    { "malayalam": "താഴ്വര", "english_transliteration": "Thazhvara", "tamil_transliteration": "தாழ்வரை", "english_meaning": "Valley", "tamil_meaning": "பள்ளத்தாக்கு" },
    { "malayalam": "അരുവി", "english_transliteration": "Aruvi", "tamil_transliteration": "அருவி", "english_meaning": "Stream / Waterfall", "tamil_meaning": "அருவி" },
    { "malayalam": "കുളം", "english_transliteration": "Kulam", "tamil_transliteration": "குளம்", "english_meaning": "Pond", "tamil_meaning": "குளம்" },
    { "malayalam": "കിണർ", "english_transliteration": "Kinaru", "tamil_transliteration": "கிணறு", "english_meaning": "Well", "tamil_meaning": "கிணறு" },
    { "malayalam": "തടാകം", "english_transliteration": "Thadakam", "tamil_transliteration": "தடாகம்", "english_meaning": "Lake", "tamil_meaning": "ஏரி / தடாகம்" },
    { "malayalam": "കായൽ", "english_transliteration": "Kayal", "tamil_transliteration": "காயல்", "english_meaning": "Backwaters / Lagoon", "tamil_meaning": "காயல்" },
    { "malayalam": "പെരുങ്കടൽ", "english_transliteration": "Perunkadal", "tamil_transliteration": "பெருங்கடல்", "english_meaning": "Ocean", "tamil_meaning": "பெருங்கடல்" },
    { "malayalam": "തിരമാല", "english_transliteration": "Thiramala", "tamil_transliteration": "திரமாலை", "english_meaning": "Wave", "tamil_meaning": "அலை" },
    { "malayalam": "പാറക്കല്ല്", "english_transliteration": "Paarakallu", "tamil_transliteration": "பாறக்கல்லு", "english_meaning": "Boulder", "tamil_meaning": "பாறாங்கல்" },
    { "malayalam": "മഞ്ഞുപാളി", "english_transliteration": "Manjupali", "tamil_transliteration": "மஞ்சுபாலி", "english_meaning": "Glacier / Ice Sheet", "tamil_meaning": "பனிப்பாறை" },
    { "malayalam": "ഹിമാലയം", "english_transliteration": "Himalayam", "tamil_transliteration": "இமாலயம்", "english_meaning": "Himalayas", "tamil_meaning": "இமாலயம்" },
    { "malayalam": "ഉൽക്ക", "english_transliteration": "Ulka", "tamil_transliteration": "உல்கா", "english_meaning": "Meteor", "tamil_meaning": "எல்கை / விண்கல்" },
    { "malayalam": "ഗ്രഹം", "english_transliteration": "Graham", "tamil_transliteration": "கிரகம்", "english_meaning": "Planet", "tamil_meaning": "கோள்" },
    { "malayalam": "ഉപഗ്രഹം", "english_transliteration": "Upagraham", "tamil_transliteration": "உபகிரகம்", "english_meaning": "Satellite", "tamil_meaning": "துணைக்கோள்" },
    { "malayalam": "വിൺപടം", "english_transliteration": "Vinpadam", "tamil_transliteration": "விண்படம்", "english_meaning": "Galaxy / Universe Space", "tamil_meaning": "விண்வெளி" },
    { "malayalam": "ബഹിരാകാശം", "english_transliteration": "Bahirakasham", "tamil_transliteration": "பஹிராாகாசம்", "english_meaning": "Outer Space", "tamil_meaning": "வெளி மண்டலம்" },
    { "malayalam": "ശാസ്ത്രജ്ഞൻ", "english_transliteration": "Shasthrajnan", "tamil_transliteration": "சாஸ்திரக்ஞன்", "english_meaning": "Scientist", "tamil_meaning": "அறிவியலாளர்" },
    { "malayalam": "ഗവേഷണം", "english_transliteration": "Gaveshanam", "tamil_transliteration": "கவேஷணம்", "english_meaning": "Research", "tamil_meaning": "ஆராய்ச்சி" },
    { "malayalam": "കണ്ടുപിടുത്തം", "english_transliteration": "Kandupidutham", "tamil_transliteration": "கண்டுபிடித்தம்", "english_meaning": "Invention / Discovery", "tamil_meaning": "கண்டுபிடிப்பு" },
    { "malayalam": "യന്ത്രം", "english_transliteration": "Yanthram", "tamil_transliteration": "யந்திரம்", "english_meaning": "Machine", "tamil_meaning": "இயந்திரம்" },
    { "malayalam": "കമ്പ്യൂട്ടർ", "english_transliteration": "Computer", "tamil_transliteration": "கம்ப்யூட்டர்", "english_meaning": "Computer", "tamil_meaning": "கணினி" },
    { "malayalam": "ഫോൺ", "english_transliteration": "Phone", "tamil_transliteration": "போன்", "english_meaning": "Phone", "tamil_meaning": "பேசி / தொலைபேசி" },
    { "malayalam": "ക്യാമറ", "english_transliteration": "Camera", "tamil_transliteration": "கேமரா", "english_meaning": "Camera", "tamil_meaning": "புகைப்படக்கருவி" },
    { "malayalam": "റേഡിയോ", "english_transliteration": "Radio", "tamil_transliteration": "ரேடியோ", "english_meaning": "Radio", "tamil_meaning": "வானொலி" },
    { "malayalam": "ടെലിവിഷൻ", "english_transliteration": "Television", "tamil_transliteration": "டெலிவிஷன்", "english_meaning": "Television", "tamil_meaning": "தொலைக்காட்சி" },
    { "malayalam": "വൈദ്യുതി", "english_transliteration": "Vaidhyuthi", "tamil_transliteration": "வைத்யுதி", "english_meaning": "Electricity", "tamil_meaning": "மின்சாரம்" },
    { "malayalam": "ബൾബ്", "english_transliteration": "Bulb", "tamil_transliteration": "பல்பு", "english_meaning": "Bulb", "tamil_meaning": "மின்விளக்கு" },
    { "malayalam": "വിശ채ീകരണം", "english_transliteration": "Vishadeekaranam", "tamil_transliteration": "விஷதீகரணம்", "english_meaning": "Explanation", "tamil_meaning": "விளக்கம்" },
    { "malayalam": "പരിഹാരം", "english_transliteration": "Pariharam", "tamil_transliteration": "பரிகாரம்", "english_meaning": "Solution", "tamil_meaning": "தீர்வு" },
    { "malayalam": "ഉപയോഗം", "english_transliteration": "Upayogam", "tamil_transliteration": "உபயோகம்", "english_meaning": "Use", "tamil_meaning": "பயன்பாடு" },
    { "malayalam": "ഉൽപന്നം", "english_transliteration": "Ulpanam", "tamil_transliteration": "உற்பன்னம்", "english_meaning": "Product", "tamil_meaning": "தயாரிப்பு" },
    { "malayalam": "വില്പന", "english_transliteration": "Vilpana", "tamil_transliteration": "வில்பன", "english_meaning": "Sale", "tamil_meaning": "விற்பனை" },
    { "malayalam": "വാങ്ങൽ", "english_transliteration": "Vanghal", "tamil_transliteration": "வாங்கல்", "english_meaning": "Buying / Purchase", "tamil_meaning": "வாங்குதல்" },
    { "malayalam": "ഉപയോക്താവ്", "english_transliteration": "Upabhokthavu", "tamil_transliteration": "உபபோக்தாவு", "english_meaning": "Consumer", "tamil_meaning": "நுகர்வோர்" },
    { "malayalam": "നിക്ഷേപം", "english_transliteration": "Nikshepam", "tamil_transliteration": "நிக்சேபம்", "english_meaning": "Investment", "tamil_meaning": "முதலீடு" },
    { "malayalam": "മുതലാളി", "english_transliteration": "Muthalali", "tamil_transliteration": "முதலாளி", "english_meaning": "Boss / Owner", "tamil_meaning": "முதலாளி" },
    { "malayalam": "തൊഴിലാളി", "english_transliteration": "Thozhilali", "tamil_transliteration": "தொழிலாளி", "english_meaning": "Worker / Laborer", "tamil_meaning": "தொழிலாளி" },
    { "malayalam": "ശമ്പളം", "english_transliteration": "Shambalam", "tamil_transliteration": "சம்பளம்", "english_meaning": "Salary / Wage", "tamil_meaning": "சம்பளம்" },
    { "malayalam": "അവധി", "english_transliteration": "Avadhi", "tamil_transliteration": "அവധി", "english_meaning": "Leave / Holiday", "tamil_meaning": "விடுமுறை" },
    { "malayalam": "വിശ്രമം", "english_transliteration": "Vishramam", "tamil_transliteration": "விஸ்ராமம்", "english_meaning": "Rest", "tamil_meaning": "ஓய்வு" },
    { "malayalam": "കളിസ്ഥലം", "english_transliteration": "Kalisthalam", "tamil_transliteration": "களிஸ்தலம்", "english_meaning": "Playground", "tamil_meaning": "விளையாட்டு மைதானம்" },
    { "malayalam": "വിനോദം", "english_transliteration": "Vinodam", "tamil_transliteration": "வினோதம்", "english_meaning": "Entertainment / Fun", "tamil_meaning": "பொழுதுபோக்கு" },
    { "malayalam": "യാത്ര", "english_transliteration": "Yathra", "tamil_transliteration": "யாத்ரா", "english_meaning": "Journey / Travel", "tamil_meaning": "பயணம்" },
    { "malayalam": "സഞ്ചാരി", "english_transliteration": "Sanchari", "tamil_transliteration": "சஞ்சாரி", "english_meaning": "Traveler / Tourist", "tamil_meaning": "பய பயணி / சுற்றுலா பயணி" },
    { "malayalam": "പര്യവേക്ഷണം", "english_transliteration": "Paryaveshanam", "tamil_transliteration": "பார்யவேஷணம்", "english_meaning": "Exploration", "tamil_meaning": "ஆய்வுப் பயணம்" },
    { "malayalam": "ദേശാടനം", "english_transliteration": "Desadanam", "tamil_transliteration": "தேசாடனம்", "english_meaning": "Migration / Tourism", "tamil_meaning": "நாடோடி பயணம்" },
    { "malayalam": "അതിർത്തി", "english_transliteration": "Athirthi", "tamil_transliteration": "அதிர்த்தி", "english_meaning": "Border / Boundary", "tamil_meaning": "எல்லை" },
    { "malayalam": "സന്ധി", "english_transliteration": "Sandhi", "tamil_transliteration": "சந்தி", "english_meaning": "Treaty / Junction", "tamil_meaning": "உடன்படிக்கை / சந்திப்பு" },
    { "malayalam": "ഒപ്പുവെക്കൽ", "english_transliteration": "Oppuvekkal", "tamil_transliteration": "ஒப்புவெக்கல்", "english_meaning": "Signing", "tamil_meaning": "கையொப்பமிடுதல்" },
    { "malayalam": "രേഖ", "english_transliteration": "Rekha", "tamil_transliteration": "ரேகா", "english_meaning": "Document / Line", "tamil_meaning": "ஆவணம் / கோடு" },
    { "malayalam": "ഒപ്പ്", "english_transliteration": "Oppu", "tamil_transliteration": "ஒப்பு", "english_meaning": "Signature", "tamil_meaning": "கையொப்பம்" },
    { "malayalam": "മുദ്ര", "english_transliteration": "Mudra", "tamil_transliteration": "முத்ரா", "english_meaning": "Stamp / Seal", "tamil_meaning": "முத்திரை" },
    { "malayalam": "അംഗീകാരം", "english_transliteration": "Angikaram", "tamil_transliteration": "அங்கீகாரம்", "english_meaning": "Approval / Recognition", "tamil_meaning": "அங்கீகாரம்" },
    { "malayalam": "നിഷേധം", "english_transliteration": "Nishedham", "tamil_transliteration": "நிஷேதம்", "english_meaning": "Denial / Prohibition", "tamil_meaning": "மறுப்பு / தடை" },
    { "malayalam": "അനുമതി", "english_transliteration": "Anumathi", "tamil_transliteration": "அனுமதி", "english_meaning": "Permission", "tamil_meaning": "அனுமதி" },
    { "malayalam": "തടസ്സം", "english_transliteration": "Thadassam", "tamil_transliteration": "தடஸ்சம்", "english_meaning": "Obstacle", "tamil_meaning": "தடை" },
    { "malayalam": "സഹകരണം", "english_transliteration": "Sahakaranam", "tamil_transliteration": "சககரணம்", "english_meaning": "Cooperation", "tamil_meaning": "ஒத்துழைப்பு" },
    { "malayalam": "മത്സരം", "english_transliteration": "Matsaram", "tamil_transliteration": "மத்ஸரம்", "english_meaning": "Competition", "tamil_meaning": "போட்டி" },
    { "malayalam": "പങ്കാളിത്തം", "english_transliteration": "Pankalitham", "tamil_transliteration": "பங்காளித்தம்", "english_meaning": "Participation", "tamil_meaning": "பங்கேற்பு" },
    { "malayalam": "വിജയി", "english_transliteration": "Vijayi", "tamil_transliteration": "விஜயி", "english_meaning": "Winner", "tamil_meaning": "வெற்றியாளர்" },
    { "malayalam": "പരാജിതൻ", "english_transliteration": "Parajithan", "tamil_transliteration": "பராஜிதன்", "english_meaning": "Loser", "tamil_meaning": "தோல்வியுற்றவர்" },
    { "malayalam": "ബഹുമതി", "english_transliteration": "Bahumathi", "tamil_transliteration": "பஹுமதி", "english_meaning": "Honor / Award", "tamil_meaning": "கௌரவம் / விருது" },
    { "malayalam": "സമ്മാനത്തുക", "english_transliteration": "Sammanathuka", "tamil_transliteration": "சமானத்துக", "english_meaning": "Prize Money", "tamil_meaning": "பரிசுத்தொகை" },
    { "malayalam": "ട്രോഫി", "english_transliteration": "Trophy", "tamil_transliteration": "ட்ரோஃபி", "english_meaning": "Trophy", "tamil_meaning": "கோப்பை" },
    { "malayalam": "പതാക", "english_transliteration": "Pathaka", "tamil_transliteration": "பதாகை", "english_meaning": "Flag", "tamil_meaning": "கொடி" },
    { "malayalam": "ദേശീയഗാനം", "english_transliteration": "Desheeyaganam", "tamil_transliteration": "தேசீயகானம்", "english_meaning": "National Anthem", "tamil_meaning": "தேசிய கீதம்" },
    { "malayalam": "ചരിത്രപുരുഷൻ", "english_transliteration": "Charithrapurushan", "tamil_transliteration": "சரித்திரபுருஷன்", "english_meaning": "Historical Figure", "tamil_meaning": "வரலாற்று நாயகன்" },
    { "malayalam": "പോരാളി", "english_transliteration": "Porali", "tamil_transliteration": "போராளி", "english_meaning": "Fighter / Revolutionary", "tamil_meaning": "போராளி" },
    { "malayalam": "വിപ്ലവം", "english_transliteration": "Viplavam", "tamil_transliteration": "விப்லவம்", "english_meaning": "Revolution", "tamil_meaning": "புரட்சி" },
    { "malayalam": "മുന്നേറ്റം", "english_transliteration": "Munnettam", "tamil_transliteration": "முன்னேற்றம்", "english_meaning": "Progress", "tamil_meaning": "முன்னேற்றம்" },
    { "malayalam": "പിന്നോക്കം", "english_transliteration": "Pinnokkam", "tamil_transliteration": "பின்னோக்கம்", "english_meaning": "Backwardness", "tamil_meaning": "பின்தங்குதல்" },
    { "malayalam": "ഭാവി", "english_transliteration": "Bhavi", "tamil_transliteration": "பாவி", "english_meaning": "Future", "tamil_meaning": "எதிர்காலம்" },
    { "malayalam": "ഭൂതകാലം", "english_transliteration": "Bhoothakalam", "tamil_transliteration": "பூதகாலம்", "english_meaning": "Past", "tamil_meaning": "கடந்த காலம்" },
    { "malayalam": "വർത്തമാനകാലം", "english_transliteration": "Varthamanakalam", "tamil_transliteration": "வர்த்தமானகாலம்", "english_meaning": "Present", "tamil_meaning": "நிகழ்காலம்" }
  ]
};

currentData.words.push(...newPayload.words);
currentData.total_words = currentData.words.length;

fs.writeFileSync(dataPath, JSON.stringify(currentData, null, 2));
console.log('Successfully appended 100 new words (Batch 5).');
